# CI.yaml --- Check OpenVox module

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  check:
    name: OpenVox ${{ matrix.puppet_version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        openvox_version: [8]

    container:
      image: ghcr.io/voxpupuli/voxbox:${{ matrix.openvox_version }}
      volumes:
        - ${{ github.workspace }}:/repo

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Lint
        run: rake -f /Rakefile lint

      - name: Validate
        run: rake -f /Rakefile validate

      - name: Unit Tests
        run: rake -f /Rakefile spec
