# CI.yaml --- Check Puppet module

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  check:
    name: Puppet ${{ matrix.puppet_version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        puppet_version: [8]

    container:
      image: ghcr.io/voxpupuli/voxbox:${{ matrix.puppet_version }}
      volumes:
        $PWD:/repo:Z

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Lint
        run: -f /Rakefile lint

      - name: Validate
        run: -f /Rakefile validate
